services:
  # Backend service
  backend:
    image: ghcr.io/humancake/sternban:main
    ports:
      - 8085:8080
    networks:
      - selfban
    environment:
      Mongo__Url: "mongodb://mongo:27017"

  # MongoDB service
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    networks:
      - selfban

  # Frontend service
  frontend:
    build:
        context: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    networks:
      - selfban

networks:
  selfban:
    driver: bridge

volumes:
  mongo-data:
